app:
  build: .
  command: bundle exec ruby app.rb
  ports:
  - "4567:4567"

  volumes:

    # Specify an absolute path mapping
    - /var/opt:/var/opt

  environment:
    - RAILS_ENV=production
    - RACK_ENV=production
